##**Import dataset destinasi wisata Indonesia**

In [ ]:
import kagglehub
import pandas as pd

In [ ]:



moview_path = kagglehub.dataset_download(
  "athreal/destinasi-wisata-dataset",
)

Downloading to /root/.cache/kagglehub/datasets/athreal/destinasi-wisata-dataset/1.archive...

100%|██████████| 127k/127k [00:00<00:00, 56.5MB/s]

Extracting files...

In [ ]:
df = pd.read_csv(moview_path + '/destinasi-wisata-indonesia.csv')

In [ ]:
df.sample(5)

,Place_Id,Place_Name,Description,Category,City,Price,Rating,Time_Minutes,Coordinate,Lat,Long,Column1,_1,Rating_Count
120,121,Candi Prambanan,Candi Prambanan atau Candi Roro Jonggrang (bah...,Budaya,Yogyakarta,50000,47,NaN,"{'lat': -7.752020600000001, 'lng': 110.4914674}",-77520206,1104914674,NaN,121,20
60,61,Tugu Proklamasi,Tugu Proklamasi adalah tugu peringatan proklam...,Budaya,Jakarta,0,46,NaN,"{'lat': -6.2030468, 'lng': 106.8466623}",-62030468,1068466623,NaN,61,26
351,352,GPIB Immanuel Semarang (Gereja Blenduk),GPIB Immanuel Semarang (populer dengan nama Ge...,Tempat Ibadah,Semarang,0,46,NaN,"{'lat': -6.968348799999999, 'lng': 110.4274767}",-69683488,1104274767,NaN,352,22
370,371,Wisata Eling Bening,Sebuah fasilitas wisata yang dikelola dengan c...,Cagar Alam,Semarang,25000,43,90.0,"{'lat': -7.253109599999999, 'lng': 110.4264512}",-72531096,1104264512,NaN,371,25
121,122,Watu Goyang,Watu Goyang ini berasal dari Bahasa Jawa yang ...,Budaya,Yogyakarta,2500,44,45.0,"{'lat': -7.9274086, 'lng': 110.4120586}",-79274086,1104120586,NaN,122,18

In [ ]:
df.Time_Minutes.unique()

array([ 15.,  90., 360.,  nan,  60.,  10., 300., 150.,  45.,  20., 180.,
       120., 240.,  30., 210.,  25.])

###**Ambil kolom yang diperlukan aja**

In [ ]:
# untuk pencarian data atau retrieval information, butuh beberapa kolom data ini aja


df = df[['Place_Name', 'Description', 'Category', 'City', 'Price', ]]

In [ ]:
df.sample(20)

,Place_Name,Description,Category,City,Price
138,Puncak Gunung Api Purba - Nglanggeran,Gunung Nglanggeran adalah sebuah gunung di Dae...,Cagar Alam,Yogyakarta,10000
303,Situ Cileunca,"Situ Cileunca yang berlokasi di Warnasari, Pan...",Cagar Alam,Bandung,2500
205,Wisata Kaliurang,"Jogja selalu menarik untuk dikulik, terlebih t...",Cagar Alam,Yogyakarta,8000
92,Gembira Loka Zoo,Kebun Binatang Gembira Loka biasa disebut Gemb...,Cagar Alam,Yogyakarta,60000
171,Pantai Indrayanti,Pantai Indrayanti menawarkan keindahan alam ya...,Bahari,Yogyakarta,10000
101,Monumen Batik Yogyakarta,Perhatian pemerintah megenai kebudayan batik i...,Budaya,Yogyakarta,40000
190,Pantai Drini,Pantai Drini adalah salah satu objek wisata ya...,Bahari,Yogyakarta,10000
429,Atlantis Land Surabaya,"Sejak diresmikan pada bulan Desember 2017, Atl...",Taman Hiburan,Surabaya,125000
251,Kampoeng Tulip,Kampoeng Tulip ialah salah satu objek wisata d...,Taman Hiburan,Bandung,15000
219,Dusun Bambu,Dusun Bambu merupakan taman rekreasi berbasis ...,Taman Hiburan,Bandung,25000
420,Museum Kesehatan Dr. Adhyatma,"Museum Kesehatan Dr. Adhyatma, MPH adalah muse...",Budaya,Surabaya,10000
261,Wot Batu,Wot Batu adalah sebuah konfigurasi energi yang...,Cagar Alam,Bandung,50000
397,Taman Buah Surabaya,Wisata Taman Buah Undaan di Surabaya adalah sa...,Taman Hiburan,Surabaya,0
240,Lawangwangi Creative Space,Lawangwangi merupakan sebuah galeri seni denga...,Taman Hiburan,Bandung,0
33,Pasar Taman Puring,Taman Puring bukanlah taman secara harfiah. Se...,Pusat Perbelanjaan,Jakarta,0
310,The Lodge Maribaya,The Lodge Maribaya adalah salah satu tempat wi...,Cagar Alam,Bandung,25000
405,Kebun Bibit Wonorejo,"Meskipun namanya kebun bibit, namun kawasan in...",Cagar Alam,Surabaya,0
15,Jembatan Kota Intan,Jembatan Kota Intan adalah jembatan tertua di ...,Budaya,Jakarta,0
154,Pantai Ngobaran,Pantai Ngobaran merupakan salah satu tempat wi...,Bahari,Yogyakarta,5000
14,Pasar Seni,Pasar Seni merupakan Pusat kerajinan dan kesen...,Pusat Perbelanjaan,Jakarta,0

In [ ]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Collecting sentence-transformers
  Downloading sentence_transformers-5.5.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Downloading sentence_transformers-5.5.1-py3-none-any.whl (588 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.9/588.9 kB 10.6 MB/s eta 0:00:00
Installing collected packages: sentence-transformers
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 5.4.1
    Uninstalling sentence-transformers-5.4.1:
      Successfully uninstalled sentence-transformers-5.4.1
Successfully installed sentence-transformers-5.5.1

In [ ]:
# pertama, kita make model sentence-indobert untuk encoder data diatas

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('firqaaa/indo-sentence-bert-base')

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/118 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: firqaaa/indo-sentence-bert-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
data = [df[i].unique().tolist() for i in df if i !='Price']

In [ ]:
sentences = ["Ibukota Perancis adalah Paris",
            "Menara Eifel terletak di Paris, Perancis",
            "Pizza adalah makanan khas Italia",
            "Saya kuliah di Carneige Mellon University"]

In [ ]:
embeddings = model.encode(sentences)

###**Gimana sih proses Tokenizer dari IndoBert dan Bert**

In [ ]:
# Model BERT

from transformers import AutoTokenizer

tokenizer_IndoBert = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

tokenizer_Bert = AutoTokenizer.from_pretrained('bert-base-uncased')

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
test_sentence = "Fasilitas di pantai ini sangat mengecewakan dan infrastrukturnya buruk."


tokens = tokenizer_IndoBert.tokenize(test_sentence)
print(tokens)

['[UNK]', 'di', 'pantai', 'ini', 'sangat', 'mengecewakan', 'dan', 'infrastruktur', '##nya', 'buruk', '.']

In [ ]:
test_sentence = test_sentence.lower()

tokens = tokenizer_IndoBert.tokenize(test_sentence)
print(tokens)

['fasilitas', 'di', 'pantai', 'ini', 'sangat', 'mengecewakan', 'dan', 'infrastruktur', '##nya', 'buruk', '.']

In [ ]:
# BERT Tokenizer
tokens_bert = tokenizer_Bert.tokenize(test_sentence)
print(tokens_bert)

['fa', '##sil', '##itas', 'di', 'pan', '##tai', 'in', '##i', 'sang', '##at', 'meng', '##ece', '##wa', '##kan', 'dan', 'in', '##fra', '##st', '##ru', '##kt', '##urn', '##ya', 'bu', '##ru', '##k', '.']

##**Decoder Transformer**

karena bagian atas sudah eksplorasi dengan `encoder` based, kita bakal coba liat gimana kalo decodernya. Jadi model bahasa seperti GPT, LLAMA, itu adalah bagian transformer `Decodernya`. Tugasnya bisanya adalah memprediksi teks selanjutnya dari sebuah kalimat. Sama kayak pas kalian prompting di AI seperti ChatGPT, Gemini dan lain-lain. (Autoregressive)

In [ ]:
# model bahasa encoder GPT-2 Yang difine tuning dengan bahasa indonesia

from transformers import GPT2Tokenizer, GPT2Model

model_name = 'cahya/gpt2-small-indonesian-522M'
tokenizer = GPT2Tokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/16.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/357 [00:00<?, ?B/s]

In [ ]:
# coba kita liat hasil tokenizernya

test_text = 'Destinasi wisata di Bali yang paling indah adalah [masked]'
encode_text = tokenizer.tokenize(test_text)

In [ ]:
encode_text

['D',
 'estinasi',
 'Ġwisata',
 'Ġdi',
 'ĠBali',
 'Ġyang',
 'Ġpaling',
 'Ġindah',
 'Ġadalah']

In [ ]:
model = GPT2Model.from_pretrained(model_name)

encode_input = tokenizer(test_text, return_tensors='pt')
output = model(**encode_input)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2Model LOAD REPORT from: cahya/gpt2-small-indonesian-522M
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |
transformer.h.{0...11}.attn.bias        | UNEXPECTED |  |
lm_head.weight                          | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
from transformers import pipeline, set_seed
generator = pipeline('text-generation', model='cahya/gpt2-small-indonesian-522M')
set_seed(42)

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: cahya/gpt2-small-indonesian-522M
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |
transformer.h.{0...11}.attn.bias        | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
generator(test_text, max_length=3, num_return_sequences=1, num_beams=10)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=3) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': 'Destinasi wisata di Bali yang paling indah adalah yang ada di Kabupaten Kudus, yaitu:\n\nKabupaten Kudus  adalah sebuah kabupaten di Provinsi Jawa Tengah, Indonesia. Ibu kota kabupaten ini terletak di Kota Kudus. Kabupaten ini berbatasan dengan Kabupaten Kudus di utara, Kabupaten Pati di timur, Kabupaten Kudus di selatan, Kabupaten Kudus di barat, serta Kabupaten Kudus di barat.\nKabupaten Kudus terdiri atas 13 kecamatan, yang dibagi lagi atas sejumlah desa dan kelurahan. Pusat pemerintahan berada di Kecamatan Kudus.\nBatas-batas wilayahnya adalah sebagai berikut:\nKabupaten Kudus terdiri atas 19 kecamatan, yang dibagi lagi atas sejumlah desa dan kelurahan. Pusat pemerintahan berada di Kecamatan Kudus.\nKabupaten Kudus terdiri atas 19 kecamatan, yang dibagi lagi atas sejumlah desa dan kelurahan. Pusat pemerintahan berada di Kecamatan Kudus.\nKabupaten Kudus terdiri atas 19 kecamatan, yang dibagi lagi atas sejumlah desa dan kelurahan. Pusat pemerintahan berada di Kecamatan Kudus.\nKabupaten Kudus terdiri atas 19 kecamatan, yang dibagi lagi atas sejumlah desa dan kelurahan. Pusat pemerintahan berada di Kecamatan Kudus.\nKabupaten Kudus terdiri atas 19 kecamatan, yang dibagi lagi atas sejumlah desa dan kelurahan. Pusat pemerintahan berada di Kecamatan Kudus.\nKabupaten Kudus terdiri atas 19 kecamatan, yang dibagi lagi atas sejumlah desa dan kelurahan. Pusat pemerintahan berada di Kecamatan Kudus.\nKabupaten Kudus terdiri atas 19 kecamatan, yang dibagi atas sejumlah desa dan kelurahan.'}]

###**Penasaran lagi nih, gimana model encoder transformer meprediksi kata selanjutnya secara probabilitynya**

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: cahya/gpt2-small-indonesian-522M
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |
transformer.h.{0...11}.attn.bias        | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
with torch.no_grad():
  outputs = model(**encode_input)

In [ ]:
skor_mentah = outputs.logits[0, -1, :]

probability = torch.nn.functional.softmax(skor_mentah, dim=-1)

top_k = torch.topk(probability, 5)

In [ ]:
print(test_text)

Destinasi wisata di Bali yang paling indah adalah

In [ ]:
for i in range(5):
  token_id = top_k.indices[i].item()
  prob_persen = top_k.values[i].item() * 100

  #decode kembali menjadi teks
  prediksi = tokenizer.decode([token_id])

  print(f"rangk {i} kata prediksi: {prediksi} - probabilitas: {prob_persen}")

rangk 0 kata prediksi:  Kuta - probabilitas: 15.302929282188416
rangk 1 kata prediksi:  Bali - probabilitas: 10.006614029407501
rangk 2 kata prediksi:  Pantai - probabilitas: 7.378724217414856
rangk 3 kata prediksi:  Pura - probabilitas: 6.850443035364151
rangk 4 kata prediksi:  wisata - probabilitas: 4.41114567220211

##**Note Tugas**

coba bandingkan model encoder antara multilingual-bert dan Indobert. Buat ringkasan dalam bentuk tulisa tangan.